{
    "type": "bundle",
    "id": "bundle--d437fdb1-ec8d-44d0-8e6b-a33ca5c4e23b",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--5615b478-f5f5-4851-a4df-d0c0ff74344b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-09-01T00:53:56.55068Z",
            "modified": "2022-09-01T00:53:56.55068Z",
            "name": "CVE-2022-1508",
            "description": "An out-of-bounds read flaw was found in the Linux kernelâ€™s io_uring module in the way a user triggers the io_read() function with some special parameters. This flaw allows a local user to read some memory out of bounds.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-1508"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}