{
    "type": "bundle",
    "id": "bundle--eb14d289-f022-49af-b14c-f6b8d6f64d33",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--bb7443bd-a6ff-4c87-97b2-53797fab26b5",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-04-29T00:46:51.474633Z",
            "modified": "2022-04-29T00:46:51.474633Z",
            "name": "CVE-2022-29818",
            "description": "In JetBrains IntelliJ IDEA before 2022.1 origin checks in the internal web server were flawed",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-29818"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}