{
    "type": "bundle",
    "id": "bundle--f1d4f811-2632-475c-8020-131a0679c749",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c747a166-0835-4cdf-b72a-0b4d1a4d2b40",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-01-31T00:29:24.909483Z",
            "modified": "2022-01-31T00:29:24.909483Z",
            "name": "CVE-2022-0413",
            "description": "Use After Free in Conda vim prior to 8.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-0413"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}