{
    "type": "bundle",
    "id": "bundle--9e14073b-f69f-43e9-af92-61c72439d8cc",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--47a8e68b-8ab2-4d4f-b870-d6984ab347ce",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-06-28T00:54:30.659254Z",
            "modified": "2022-06-28T00:54:30.659254Z",
            "name": "CVE-2022-31093",
            "description": "NextAuth.js is a complete open source authentication solution for Next.js applications. In affected versions an attacker can send a request to an app using NextAuth.js with an invalid `callbackUrl` query parameter, which internally is converted to a `URL` object. The URL instantiation would fail due to a malformed URL being passed into the constructor, causing it to throw an unhandled error which led to the **API route handler timing out and logging in to fail**. This has been remedied in versions 3.29.5 and 4.5.0. If for some reason you cannot upgrade, the workaround requires you to rely on Advanced Initialization. Please see the documentation for more.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-31093"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}